### ISSUE TITLE
Some grid events contain invalid player ids

### ISSUE THREAD

**Issue by mgerhardy** [iteratec/traze-gameserver#2]
I suppose this is due to fact that the player info and grid info are sent with different timings or something like that. But sometimes I receive invalid player ids (just for a few seconds) in a grid - then get the player info with the new ids in. This leads to jumps in the board. You sometimes see players spawning with a bike length > 2

**Comment by asciijungle** [comment]
Hi @mgerhardy thanks for your ticket and sorry for the late reply!
The player ids are integer numbers that are being reused. For example if there are three players `[ 1, 2, 3 ]` and player 2 dies the next joining player will get player ID 2. We've seen that cause some confusion previously.

However players spawning with a bike length > 2 would be new to me. Do you have any way to reproduce this behavior? Or any kind of record what happened exactly?

**Comment by mgerhardy** [comment]
Reusing player ids is not a problem for me.

The "problem" here is that you sometimes get board information about players where you didn't receive the player info for (yet). So imagine a new player spawns, you get the board data with the new player id. But after that happens you get the player details about that new player the first time - because the timeslices of the events were overlapping. That means the board information you received a few millis before must get trashed.

This isn't a big issue, but sometimes lead to jumping player starts - because afair there are 500ms between the grid updates - and that is visible if you have to skip 1 or 2 frames. This only happens when a lot of players are spawning at the same time btw.

**Comment by asciijungle** [comment]
Thanks for giving a more in depth description of the issue. I understand why this is an issue in some circumstances. I think the best solution here is to use the retained message flag on messages on the player topic and only publish a new list once a new player joins or a player leaves the grid.
I'll be working on a fix for that.

**Comment by asciijungle** [comment]
grid and players messages are now being sent at the same time.
